#!/bin/bash

if [ -d infcontWork/"${1}"/"${2}" ];
then
    echo "problem exists. exit"
    exit 1
fi
cd infcontWork
mkdir "${1}"/"${2}"
cp ../etc/skeleton${3}.cc "${1}"/"${2}"/main.cc
cd "${1}"/"${2}"
touch in

