#!/bin/bash
# ad-hoc script
akt=$(pwd|awk -F/ '{print $NF}')
#echo ${akt}
#exit
cp -R "${1}" ../../pass/"${akt}"

find "${1}" -type f -name '*.cc' -print0 |
while IFS= read -r -d '' file; do
    nev=$(printf '%s\n' "$file")
#    echo "${nev}"
   cat "${nev}" | ~/.config/hide/hide ~/.config/hide/uj > "${nev}".sec
   rm "${nev}"
done
mv "${1}" ../../pass.sec/"${akt}"
